### PR TITLE
Muted tabs should retain speaker icon even if no sound is playing

### PR DESCRIPTION
**Pull request by pip25**
This works fine for me, although maybe adding a preference for this would be ideal.

### CODE REVIEW

**Comment by adisib** [comment]
Other than what I mentioned on the upstream issue, I have one concern. The setIconForTab function is likely not supposed to have a conditional effect; it simply makes the icon into whatever you tell it, and I don't think that should be changed. I think the better place to have conditional logic is the place where you decide which icon to pass into the setIconForTab function, which only occurs around line 188.

So I think the better change is:
```Javascript
function updateIconForTab(tab) {
    if (tab) {
        let browser = tab.linkedBrowser;
        if (browser) {
            let document = browser.contentDocument;

            let states = {
                playing: false,
                playingMuted: false
            };

            updateStatesForDocument(states, document);

            if (states.playing && !tabMuted) {
                setIconForTab(tab, STATE_PLAYING);
            } else if (states.playingMuted || tabMuted) {
                setIconForTab(tab, STATE_PLAYING_MUTED);
            } else if (hasTabIcon(tab)) {
                setIconForTab(tab, STATE_NOT_PLAYING);
            }
        }
    }
}
```

**Comment by pip25** [comment]
Sure, but in this case the STATE_PLAYING_MUTED needs to be renamed as well, since it no longer indicates that anything is actually playing on the page. Updated the request.

**Comment by pip25** [comment]
Updated. Now if the sound was muted by on-page controls, the normal speaker icon remains in the tab. The muted icon is only shown if the tab was muted by the extension.

**Comment by adisib** [comment]
Making the state separate from what is happening on the page also means that updateStatesForDocument should be modified to not report on whether elements are muted on the page. I think muted elements should count as not playing probably, but I'm not sure. States can then just be replaced with a bool called something like isPlaying, and updateStatesForDocument probably should be renamed as well.

I can accept the pull request now if you think that leaving that functionality in might come in handy later even if it isn't used anymore now, or if you want to make that change in a separate PR or leave it for me to do.

**Comment by pip25** [comment]
I considered this as well, but arrived to the conclusion that we might need it later if we want some more nuanced "mute detection". For instance, currently, if you mute a Youtube video using the player, then click the speaker icon twice (to set and then unset the flag), it will unmute the video even though it was not muted by the extension in the first place (and the player UI will still show the video as muted).
This isn't a very serious issue, but could theoretically be solved by some additional work where we check if something was already muted on the page when the speaker icon was clicked, and remember that those do not need unmuting later on.

**Pull request merged**
